server:
  port: 2244
  shutdown: graceful

spring:
  application:
    name: RabbitMQWithMQTTProtocol

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

mqtt:
  broker:
    url: tcp://localhost:1883
  client:
    id: spring-mqtt-client
  topic: sensors/temperature